name: Create PreProd Stacks and Run Integration Tests
on:
  push:
    branches:
      - master

jobs:
  create-preprod-list-reconciliation-stack:
    name: Create PreProd List Reconciliation Stack
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Python Package
        # TODO this will be remove when using a shared packaging step
        run: |
          python -m pip install --upgrade pipenv
          PATH=$PATH:/opt/github_runner/.local/bin make python-package
      - name: Terraform Init
        run: |
          make init
          make workspace env="preprod"
      - name: Terraform Validate
        run: |
          make validate
      - name: Terraform Apply
        run: |
          make apply
      - name: Upload terraform output artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform_outputs
          path: ./terraform_outputs_list-reconciliation.json
          retention-days: 2

  create-preprod-mesh-stack:
    name: Create preprod Mesh stack on AWS
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Init
        run: |
          make init stack="mesh"
          make workspace env="preprod" stack="mesh"
      - name: Terraform Validate
        run: |
          make validate stack="mesh"
      - name: Terraform Apply
        run: |
          make apply stack="mesh"

  run-integration-tests:
    name: Run Integration Tests
    runs-on: self-hosted
    needs:
      - create-preprod-list-reconciliation-stack
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: terraform_outputs
      - name: Assume Role in PreProd Account for Integration Tests
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: "arn:aws:iam::287634746327:role/LRTerraformDeploy"
          role-duration-seconds: 1200
      - name: Run Integration tests
        run: |
          # Ensure gpextract and mock_data install location is available to Gauge
          export PATH=$PATH:/opt/github_runner/.local/bin
          make integrationtest-deps
          make integrationtests-preprod
      - name: Upload Integration tests result artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: integration_test_report
          path: test/integrationtests/reports/html-report/*
          retention-days: 2
      - name: Upload Integration tests logs artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: integration_test_logs
          path: test/integrationtests/logs/*
          retention-days: 2
