name: Create Test List Reconciliation Stack and run Integration Tests
on:
  push:
    branches:
      - develop

jobs:
  create-test-list-reconciliation-stack:
    name: Create Test List Reconciliation Stack
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Python Package
        run: |
          make python-package
      - name: Terraform Init
        run: |
          make init
          make workspace env="test"
      - name: Terraform Validate
        run: |
          make validate
      - name: Terraform Apply
        run: |
          make apply
      - name: Upload terraform output artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-output
          path: ./terraform_outputs_list-reconciliation.json
          retention-days: 2

  run-integration-tests:
    name: Run Integration Tests
    runs-on: self-hosted
    needs:
      - create-test-list-reconciliation-stack
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: terraform-output
      - name: Assume Role in Dev Account for Integration Tests
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: "arn:aws:iam::092420156801:role/LRTerraformDeploy"
          role-duration-seconds: 1200
      - name: Run Integration tests
        run: |
          # Ensure gpextract and mock_data install location is available to Gauge
          export PATH=$PATH:/opt/github_runner/.local/bin
          make integrationtest-deps
          make integrationtests
      - name: Upload Integration tests result artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: integration_test_report
          path: test/integrationtests/reports/html-report/*
          retention-days: 2
      - name: Upload Integration tests logs artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: integration_test_logs
          path: test/integrationtests/logs/*
          retention-days: 2
