name: Deploy Test infrastructure on AWS
on:
  push:
    branches:
      - develop
jobs:
  deploy-test-Infra:
    name: Deploy Test Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Init
      run: |
        echo "Depolying 'Test' infrastructure "
        rm -rf .terraform || true
        make init deployment_environment=test
        terraform -chdir=terraform/environment/test workspace select test || terraform -chdir=terraform/environment/test workspace new test
        terraform -chdir=terraform/environment/test workspace list
    - name: Terraform Apply
      run: |
          terraform -chdir=terraform/environment/test apply -auto-approve
    - name: Terraform output
      run: |
        terraform -chdir=terraform/environment/test output -json > output.json
    - name: upload terraform output artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform output
        path: output.json
        retention-days: 2
    - name: Run System tests
      run: |
          cat output.json
          echo "Running System tests"