name: Destroy feature branch infrastructure on AWS
on:
  pull_request:
    types:
      - closed
    branches-ignore:
      - master

jobs:
  destroy-feature-branch-infra:
    name: Destroy feature branch infrastructure on AWS
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      FEATURE_BRANCH: ${GITHUB_HEAD_REF##*/}
    steps:
      - uses: actions/checkout@v2
      - name: Python Package
        run: |
          make python-package
      - name: Terraform Init
        run: |
          make init
          make workspace env=$(make get-branch-id branch=${{ env.FEATURE_BRANCH }})
      - name: Terraform Destroy
        run: |
          make destroy
      - name: Terraform Delete workspace
        run: |
          make workspace-delete env=$(make get-branch-id branch=${{ env.FEATURE_BRANCH }})
